import type { FastifyInstance } from "fastify";
import { registerAlertProjectsRoutes } from "./alert-projects.routes.js";
import { registerAlertsRoutes } from "./alerts.routes.js";
import { registerAssetsRoutes } from "./assets.routes.js";
import { registerAutomationsRoutes } from "./automations.routes.js";
import { registerBossFightRoutes } from "./boss-fight.routes.js";
import { registerChatCommandsRoutes } from "./chat-commands.routes.js";
import { registerChatChaosRoutes } from "./chat-chaos.routes.js";
import { registerChatQuotesRoutes } from "./chat-quotes.routes.js";
import { registerChatTimersRoutes } from "./chat-timers.routes.js";
import { registerConfigRoutes } from "./config.routes.js";
import { registerEffectsRoutes } from "./effects.routes.js";
import { registerEmergencyRoutes } from "./emergency.routes.js";
import { registerGoalsRoutes } from "./goals.routes.js";
import { registerGiveawaysRoutes } from "./giveaways.routes.js";
import { registerHealthRoutes } from "./health.routes.js";
import { registerIntegrationsRoutes } from "./integrations.routes.js";
import { registerLoyaltyRoutes } from "./loyalty.routes.js";
import { registerLogsRoutes } from "./logs.routes.js";
import { registerMacrosRoutes } from "./macros.routes.js";
import { registerMiniGamesRoutes } from "./mini-games.routes.js";
import { registerObsRoutes } from "./obs.routes.js";
import { registerOverlayPacksRoutes } from "./overlay-packs.routes.js";
import { registerOverlayThemeRoutes } from "./overlay-theme.routes.js";
import { registerOverlaysRoutes } from "./overlays.routes.js";
import { registerPredictionsRoutes } from "./predictions.routes.js";
import { registerSessionsRoutes } from "./sessions.routes.js";
import { registerSourceGroupsRoutes } from "./source-groups.routes.js";
import { registerStreamDeckRoutes } from "./streamdeck.routes.js";
import { registerThemesRoutes } from "./themes.routes.js";
import { registerTournamentScoreboardRoutes } from "./tournament-scoreboard.routes.js";
import type { ServerContext } from "./types.js";
import { registerViewerQueueRoutes } from "./viewer-queue.routes.js";
import { registerWebhooksRoutes } from "./webhooks.routes.js";
import { registerWidgetsRoutes } from "./widgets.routes.js";

export function registerRoutes(app: FastifyInstance, oauthApp: FastifyInstance, ctx: ServerContext): void {
  registerHealthRoutes(app, ctx);
  registerLogsRoutes(app, ctx);
  registerConfigRoutes(app, ctx);
  registerSessionsRoutes(app, ctx);
  registerStreamDeckRoutes(app, ctx);
  registerOverlaysRoutes(app, ctx);
  registerOverlayPacksRoutes(app, ctx);
  registerOverlayThemeRoutes(app, ctx);
  registerThemesRoutes(app, ctx);
  registerTournamentScoreboardRoutes(app, ctx);
  registerPredictionsRoutes(app, ctx);
  registerBossFightRoutes(app, ctx);
  registerChatChaosRoutes(app, ctx);
  registerAlertProjectsRoutes(app, ctx);
  registerAssetsRoutes(app, ctx);
  registerAlertsRoutes(app, ctx);
  registerWidgetsRoutes(app, ctx);
  registerGoalsRoutes(app, ctx);
  registerGiveawaysRoutes(app, ctx);
  registerWebhooksRoutes(app, ctx);
  registerEffectsRoutes(app, ctx);
  registerEmergencyRoutes(app, ctx);
  registerChatCommandsRoutes(app, ctx);
  registerChatQuotesRoutes(app, ctx);
  registerChatTimersRoutes(app, ctx);
  registerLoyaltyRoutes(app, ctx);
  registerViewerQueueRoutes(app, ctx);
  registerMiniGamesRoutes(app, ctx);
  registerMacrosRoutes(app, ctx);
  registerAutomationsRoutes(app, ctx);
  registerSourceGroupsRoutes(app, ctx);
  registerObsRoutes(app, ctx);
  registerIntegrationsRoutes(app, oauthApp, ctx);
}
